communication:
  b_route_id: 00112233445566778899AABBCCDDEEFF
  b_route_password: 0123456789AB
  echonet_port: 3610
  wi_sun_channel: null
  wi_sun_device: /dev/ttyUSB0
echonet:
  battery_id: FE00000000000000000000000000000300
  battery_rated_capacity_wh: 10000.0
  maker_code: '000106'
  node_profile_id: FE00000000000000000000000000000100
  smart_meter_id: FE00000000000000000000000000000000
  solar_id: FE00000000000000000000000000000200
  v2h_battery_capacity_wh: 50000.0
  v2h_charge_power_w: 3000.0
  v2h_discharge_power_w: 3000.0
  v2h_id: FE00000000000000000000000000000500
  water_heater_id: FE00000000000000000000000000000400
  water_heater_power_w: 1000.0
  water_heater_tank_capacity: 370
  wifi_devices:
  - solar
  - battery
  - water_heater
  - v2h
simulation:
  scenario_file: data/default_scenario.csv
  update_interval_sec: 1.0
system:
  log_level: INFO
